### ISSUE TITLE
Autocmake python script works with error

### ISSUE THREAD

**Issue by TaiXeflar** [fritzone/autocmake#2]
Hi, I'm transfering a automake project(vermaseren/form) to cmake project with this `auto2cmake.py` script. I'm put this Python File to the form project folder and run directly(no any changes in `auto2cmake.py`), the terminal console returns error like this:
```
 Traceback (most recent call last):
  File "./auto2cmake.py", line 1647, in <module>
    main(sys.argv[1:])
  File "./auto2cmake.py", line 1641, in main
    convert()
  File "./auto2cmake.py", line 1466, in convert
    process_configure_ac(configure_ac)
  File "./auto2cmake.py", line 997, in process_configure_ac
    current_line = content[i].strip()
 IndexError: list index out of range
```
Is this error generated by no pre-setup or anything else? I'm not very sure how to use this convert tool.

P.S. Tested on windows 11 and linux platform.

Thanks

**Comment by RainyLave** [comment]
Same error~

**Comment by fritzone** [comment]
> Same error~
> 

Can you please provide the script you are trying to convert? I wrote this tool for one of my projects, worked for that and never ever have thought that anyone else would need to use it. Thanks.

**Comment by marin-man** [comment]
https://github.com/build-system-experiments/cmake-for-cpython/blob/cmake/configure.ac

**Comment by marin-man** [comment]
> > Same error~
> 
> Can you please provide the script you are trying to convert? I wrote this tool for one of my projects, worked for that and never ever have thought that anyone else would need to use it. Thanks.

https://github.com/python/cpython/blob/main/configure.ac

**Comment by Static-Codes** [comment]
I was able to get cpython compiling as intended in the included unit tests in my pull request here: https://github.com/fritzone/autocmake/pull/8

Unit test commit: https://github.com/fritzone/autocmake/pull/8/changes/65f005c8c3ab1b6befd825d0d7ce8394f77c71b6

Log:
```python3 tests/run_tests.py
Running Test #1

Action 1/5: Cloning the repository from: https://github.com/gpg/gnupg

Action 2/5: Cleaning up existing CMakeLists.txt in gnupg

Action 3/5: Running auto2cmake.py for gnupg

Action 4/5: Attempting to configure gnupg using CMake

SUCCESS: gnupg configured with CMake!

Action 5/5: Removing build artifacts associated with this test.

SUCCESS: Removed build artifacts associated with this test.


Running Test #2

Action 1/5: Cloning the repository from: https://github.com/gpg/gnupg

Action 2/5: Cleaning up existing CMakeLists.txt in gnupg

Action 3/5: Running auto2cmake.py for gnupg

Action 4/5: Attempting to configure gnupg using CMake

SUCCESS: gnupg configured with CMake!

Action 5/5: Removing build artifacts associated with this test.

SUCCESS: Removed build artifacts associated with this test.


Test #1: Passed
Test #2: Passed




======================================
Test Statistics
======================================
Total Tests: 2
Passed Tests: 2
Failed Tests: 0

Success Rate: 100.0%
Failure Rate: 0.0%
```

**Comment by Static-Codes** [comment]
@fritzone My previous comment didnt properly reflect the state of this issue, it has been successfully addressed!

Below you will find the updated test results from [run_tests.py](https://github.com/fritzone/autocmake/blob/master/tests/run_tests.py)

```bash
Running Test #1
Test Description: Testing compatibility with gnupg using a supported legacy version of CMake (3.1)

Action 1/5: Cloning the repository from: https://github.com/gpg/gnupg

Action 2/5: Cleaning up existing CMakeLists.txt in gnupg

Action 3/5: Running auto2cmake.py for gnupg
Command: python3 /home/nerdy/repos/SCB/Deps/autocmake/auto2cmake.py -d /home/nerdy/repos/SCB/Deps/autocmake/gnupg -v 3.1

Action 4/5: Attempting to configure gnupg using CMake 3.1

SUCCESS: gnupg configured with CMake 3.1!

Action 5/5: Removing build artifacts associated with this test.

SUCCESS: Removed build artifacts associated with this test.


Running Test #2
Test Description: Testing compatibility with cpython, which caused issues in older releases of auto2cmake.

Action 1/5: Cloning the repository from: https://github.com/python/cpython

Action 2/5: Cleaning up existing CMakeLists.txt in cpython

Action 3/5: Running auto2cmake.py for cpython
Command: python3 /home/nerdy/repos/SCB/Deps/autocmake/auto2cmake.py -d /home/nerdy/repos/SCB/Deps/autocmake/cpython -v 3.28.3

Action 4/5: Attempting to configure cpython using CMake 3.28.3

SUCCESS: cpython configured with CMake 3.28.3!

Action 5/5: Removing build artifacts associated with this test.

SUCCESS: Removed build artifacts associated with this test.


Running Test #3
Test Description: Testing the version parsing logic against an unsupported version of CMake (2.7)

Action 1/5: Cloning the repository from: https://github.com/gpg/gnupg

Action 2/5: Cleaning up existing CMakeLists.txt in gnupg

Action 3/5: Running auto2cmake.py for gnupg
Command: python3 /home/nerdy/repos/SCB/Deps/autocmake/auto2cmake.py -d /home/nerdy/repos/SCB/Deps/autocmake/gnupg -v 2.7

SUCCESS: Test passed!


Running Test #4
Test Description: Testing the version parsing logic against an unreleased version of CMake (6.9)

Deleting old test artifact at: /home/nerdy/repos/SCB/Deps/autocmake
Deleted old test artifact.

Action 1/5: Cloning the repository from: https://github.com/gpg/gnupg

Action 2/5: Cleaning up existing CMakeLists.txt in gnupg

Action 3/5: Running auto2cmake.py for gnupg
Command: python3 /home/nerdy/repos/SCB/Deps/autocmake/auto2cmake.py -d /home/nerdy/repos/SCB/Deps/autocmake/gnupg -v 6.9

SUCCESS: Test passed!


Test #1: Passed
Test #2: Passed
Test #3: Passed
Test #4: Passed




======================================
Test Statistics
======================================
Total Tests: 4
Passed Tests: 4
Failed Tests: 0

Success Rate: 100.0%
Failure Rate: 0.0%
```

**Comment by fritzone** [comment]
Thanks again for the effort invested :)

**Comment by Static-Codes** [comment]
Likewise to you! I couldn't have gotten this far without your initial work! The gratitude is mutual :)
